package config

// EmitterSecrets holds all Emitter information and channel keys
var EmitterSecrets = map[string]string{
	"license":                  "zs39gyr2ThwMwfa3oDLPRWHrAoUgVMApAAAAAAAAAAI",
	"secret":                   "h3C7sXwQy0GO0FBNCMPxjoxa7vdftXkv",
	"config":                   "QcrrTb0B4Ta43CjR1dqHalXExdDF0NwX",
	"config/flux":              "",
	"state/hue/flux":           "",
	"state/yee/flux":           "",
	"state/sensor/aqi":         "",
	"config/aqi":               "",
	"config/tv/sony":           "",
	"state/tv/sony":            "",
	"config/tv/samsung":        "",
	"state/tv/samsung":         "",
	"config/presence":          "",
	"state/sensor/presence":    "",
	"config/calendar":          "",
	"state/sensor/caledar":     "",
	"state/sensor/season":      "",
	"config/suncalc":           "",
	"state/sensor/sun":         "",
	"config/weather":           "",
	"state/sensor/clouds":      "",
	"state/sensor/wind":        "",
	"state/sensor/rain":        "",
	"state/sensor/temperature": "",
	"config/wemo":              "",
	"state/wemo":               "",
	"config/xiaomi":            "",
	"state/xiaomi/switch":      "",
	"state/xiaomi/gateway":     "",
	"state/sensor/battery":     "",
	"state/sensor/motion":      "",
	"config/hue":               "",
	"state/hue/light":          "",
	"config/yee":               "",
	"state/yee/light":          "",
}
